<a href="https://colab.research.google.com/github/RNeoMM/masai/blob/main/Power_Tools_%26_OptimisingNumerical_codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [ ]:
a[0] = 100

In [ ]:
a

array([100,   1,   2,   3])

In [ ]:
b

array([[100,   1],
       [  2,   3]])

In [ ]:
#Deep Copy
a = np.arange(4)
c = a + 2
c

array([2, 3, 4, 5])

In [ ]:
a[0] = 109
a

array([109,   1,   2,   3])

In [ ]:
c

array([2, 3, 4, 5])

In [ ]:
a= np.arange(10)

# Slicing creates shallow copies
b= a[::2]
print(a,b)

[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]


In [ ]:
np.shares_memory(a,b)

True

In [ ]:
#Shallow Copy --> Reshaping,Slicing...
#deep Copy --> Arithmetic,Masking Operations..
a = np.arange(6) #0,1,2,3,4,5
b = a[a % 1 == 0] #10,1,2,3,4,5

In [ ]:
b[0] = 10
a[0]

np.shares_memory(a,b)

False

In [ ]:
#view() --> returns view of orginal array, any changes made in new array will be reflected in org array

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample_arr = arr.view()
sample_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample_arr[4]= 1234
np.shares_memory(arr,sample_arr)

True

In [ ]:
#copy() --> returna a copy of array , changes made in new array are not reflected in org array

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_demo = arr.copy()
copy_demo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy_demo[3] = 100
np.shares_memory(arr,copy_demo)

False

In [ ]:
copy_demo

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#profiling

#%timeit --> Quick Performance Checks

arr = np.arange(1000000)

#python loops
def squares(a):
  result = []
  for x in a:
    result.append(x ** 2)
  return result

#numpy
def square_numpy(a):
  return a ** 2

In [ ]:
%timeit squares(arr)
%timeit square_numpy(arr)

208 ms ± 15.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.14 ms ± 128 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
#using Time Module
import time

arr = np.arange(1000000)

strt = time.time()
result = np.square(arr)
end = time.time()

print(f"Execution Time: {end - strt:.5f} seconds")

Execution Time: 0.00294 seconds


In [ ]:
#cprofile --> shows how much time each function in your program takes

import cProfile

def compute():
  x = np.random.rand(1000,1000)
  y = np.dot(x,x.T)
  z = np.linalg.inv(y[:100,:100])
  return z.sum()

In [ ]:
cProfile.run('compute()')

         603 function calls (597 primitive calls) in 0.083 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    0.000    0.000 <frozen abc>:121(__subclasscheck__)
        5    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:1390(_handle_fromlist)
        1    0.000    0.000    0.080    0.080 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _base.py:337(_invoke_callbacks)
        1    0.000    0.000    0.000    0.000 _base.py:537(set_result)
        1    0.000    0.000    0.000    0.000 _linalg.py:123(_makearray)
        2    0.000    0.000    0.000    0.000 _linalg.py:128(isComplexType)
        1    0.000    0.000    0.000    0.000 _linalg.py:142(_realType)
        1    0.000    0.000    0.000    0.000 _linalg.py:148(_commonType)
        1    0.000    0.000    0.000    0.000 _linalg.py:192(_assert_stacked_2d)
        1    0.000    0.000    0.000    0.000 _linalg.py:

In [ ]:
#line Profiler --> advance line by line profiling

!pip install line_profiler

from line_profiler import LineProfiler
import numpy as np

def matrix_ops():
    a = np.random.rand(1000, 1000)
    b = np.random.rand(1000, 1000)
    c = np.dot(a, b)
    d = np.linalg.svd(c)
    return d

lp = LineProfiler()
lp.add_function(matrix_ops)
lp.run('matrix_ops()')
lp.print_stats()

Timer unit: 1e-09 s

Total time: 0.95294 s

Could not find file /tmp/ipython-input-1693393343.py
Are you sure you are running this program from the same directory
that you ran the profiler from?
Continuing without the function's contents.

Line #      Hits         Time  Per Hit   % Time  Line Contents
     8                                           
     9         1    9911606.0 9.91e+06      1.0  
    10         1    8617778.0 8.62e+06      0.9  
    11         1   59239187.0 5.92e+07      6.2  
    12         1  875169051.0 8.75e+08     91.8  
    13         1       2803.0   2803.0      0.0  



In [ ]:
#vectorization
data = [1,2,3,4,5]

sq_loop = [x ** 2 for x in data]
print("my loop",sq_loop)

my loop [1, 4, 9, 16, 25]


In [ ]:
#vectorized power
arr = np.array(data)
my_final = arr ** 2
print("my loop",my_final)

my loop [ 1  4  9 16 25]


In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def random_operation([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2

    return x

In [ ]:
random_operation(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
get_the_solution = np.vectorize(random_operation)
type(get_the_solution)

numpy.vectorize

In [ ]:
get_the_solution(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])